server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: main-topic

telegram-bot:
  username: qqCheckYourStatsBot
  token: 7648929656:AAGdCnHfrLYd7zG7xjGeqm6r9E0UcagvUWE
  webhook-uri: https://bd1b-79-104-7-208.ngrok-free.app

project:
  node:
    api: http://localhost:8081/node/api
