server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic-message: message-topic
    topic-file: file-topic
    group-id:
      string: string-group
      document: document-group