server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic-message-to-dispatcher: message-topic-to-dispatcher
    topic-message: message-topic-from-dispatcher
    topic-file: file-topic-from-dispatcher
    group-id:
      from-dispatcher: from-dispatcher
      to-dispatcher: to-dispatcher